---
title: "Exercise 1 Solution Key"
author: "Ozancan Ozdemir"
output: word_document
date: '2022-11-05'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Question 1 

**1.a)**

```{r}
((3/8)*7)+12
```

**1.b)**

```{r}
log(15)
```

**1.c)**

```{r}
sqrt(8)
```

### Question 2

```{r}
C<-c(37,27,14)

Fah<- ((C*9)/5)+32

Fah
```


### Question 3

**3.a)**

```{r}
rep(seq(-10,10,2),3)
```

**3.b)**

```{r}
rep(seq(-10,10,2),rep(3,11))
```


**3.c)**

```{r}
c(seq(2,8,2),seq(8,2,-2))
```

**3.d)**

```{r}
a<-c("1","2","3","red")
rep(a,3)
```


**3.e)**

```{r}
rep(c(2,3,5),seq(4,2,-1))

```


### Question 4

Here, I will create my matrices by using ```matrix``` and ```c``` object. 

```{r}
A=matrix(c(1.2,2.45,1.46,1.3,0.89,4.12,0.5,1.6,8.1),ncol=3)
B=matrix(c(1.8,2,1,8.1,1.9,1.9,1.9,2.3,3.8),ncol=3)
```


**4.a)**

```{r}
A*B
```

**4.b)**

```{r}
solve(A) #inverse of A
t(A) #transpose of A
```

```{r}
solve(B) #inverse of B
t(B) #transpose of B
```

**4.c)**

```{r}
A-B
A+B
```


### Question 5

As in the previous question, I will create my matrices by using ```matrix``` and ```c``` object. Then, I name columns by using ```colnames()``` function. Note that you can solve this question using ```data.frame```. 

```{r}
m<-matrix(c(20,21,22,23,12,14,12,16,40,45,45,80),ncol=3)
print(m)
```

```{r}
colnames(m)=c("Length","Speed","Algae")

```


**5.a)**

```{r}
m[3,"Algae"]
```

**5.b)**


```{r}
m[3,]
```
**5.c)**


```{r}
m[c(1,3),]
```

**5.d)**


```{r}
m[,"Speed"]
```

**5.e)**


```{r}
m[,c("Length","Speed")]
```